#!/bin/bash
for file in *.csproj; do
	if [[ $file == *Tests* ]]; then
		sourcetype='tests'
	else
		sourcetype='src'
	fi
	if [[ $file =~ Cinema\.([a-zA-Z]+).* ]]; then
		microservice="${BASH_REMATCH[1]}"
	else
		echo "Can't find service name for $file"
		exit 1
	fi
	project=`basename -s .csproj $file`
	mkdir -p $microservice/$sourcetype/$project
	mv $file $microservice/$sourcetype/$project
done

